# fly.toml app configuration file generated for micro-blog on 2023-11-14T16:43:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "micro-blog"
primary_region = "otp"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
